// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/life-gradient/Preview.tsx": () => import("../components/mockups/life-gradient/Preview.tsx"),
  "./components/mockups/music-apple/Preview.tsx": () => import("../components/mockups/music-apple/Preview.tsx"),
  "./components/mockups/music-heading-b/Preview.tsx": () => import("../components/mockups/music-heading-b/Preview.tsx"),
  "./components/mockups/music-heading-c/Preview.tsx": () => import("../components/mockups/music-heading-c/Preview.tsx"),
  "./components/mockups/music-heading-a/Preview.tsx": () => import("../components/mockups/music-heading-a/Preview.tsx"),
  "./components/mockups/music-hub/Preview.tsx": () => import("../components/mockups/music-hub/Preview.tsx"),
  "./components/mockups/music-mymusic/Preview.tsx": () => import("../components/mockups/music-mymusic/Preview.tsx"),
  "./components/mockups/music-hub-glass/Preview.tsx": () => import("../components/mockups/music-hub-glass/Preview.tsx"),
  "./components/mockups/music-spotify/Preview.tsx": () => import("../components/mockups/music-spotify/Preview.tsx")
};
