// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/life-gradient/Preview.tsx": () => import("../components/mockups/life-gradient/Preview.tsx"),
  "./components/mockups/music-hub/Preview.tsx": () => import("../components/mockups/music-hub/Preview.tsx")
};
